name: Update README with Recent Features (Scheduled)

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 50  # Get the last 50 commits

      - name: Create new branch for auto-update (Repo)
        run: git checkout -B update-readme

      - name: Retrieve recent feature commits and update readme
        run: |
          echo "### 🔄 Recently Worked On" > recent_commits.md
          echo "" >> recent_commits.md
          echo "| Feature | Last Commit | Workflow Updated |" >> recent_commits.md
          echo "|---------|-------------|------------------|" >> recent_commits.md
          last_run=$(TZ=Europe/Berlin date '+%Y-%m-%d %H:%M:%S %Z')
          echo "$last_run" > last_run.txt
          git log -E --grep="^feat:" -5 --pretty=format:"| %s | %ar | $last_run |" \
            | sed -E 's/^\| feat:[[:space:]]*/| /' \
            >> recent_commits.md || echo "| No recent features | - | - |" >> recent_commits.md
      
      - name: Update Repository README
        run: |
          CONTENT=$(cat recent_commits.md | sed 's/\//\\\//g' | sed ':a;N;$!ba;s/\n/\\n/g')
          sed -i "/<!-- START_RECENTLY_WORKED_ON -->/,/<!-- END_RECENTLY_WORKED_ON -->/c\<!-- START_RECENTLY_WORKED_ON -->\n$CONTENT\n<!-- END_RECENTLY_WORKED_ON -->" README.md

      - name: Commit and Push Changes (Repo README)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Auto-update Recently Worked On section (Scheduled)" || exit 0
          git push origin update-readme --force

      - name: Checkout Profile Repository
        uses: actions/checkout@v3
        with:
          repository: "goldbarth/goldbarth"  # GitHub-Profile
          token: ${{ secrets.PAT_TOKEN }}
          path: profile_repo
          fetch-depth: 0  # Fetches the entire Git history to avoid merge conflicts

      - name: Create new branch for auto-update (Profile)
        run: | 
          cd profile_repo
          git checkout -B update-readme

      - name: Update GitHub Profile README
        run: |
          CONTENT=$(cat recent_commits.md | sed 's/\//\\\//g' | sed ':a;N;$!ba;s/\n/\\n/g')
          sed -i "/<!-- START_RECENTLY_WORKED_ON -->/,/<!-- END_RECENTLY_WORKED_ON -->/c\<!-- START_RECENTLY_WORKED_ON -->\n$CONTENT\n<!-- END_RECENTLY_WORKED_ON -->" profile_repo/README.md

      - name: Commit and Push Changes (Profile README)
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd profile_repo
          git config --global user.name "goldbarth"
          git config --global user.email "felix.wahl@live.com"
          git remote set-url origin https://x-access-token:${PAT_TOKEN}@github.com/goldbarth/goldbarth.git
          git add README.md
          git commit -m "Auto-update Recently Worked On section (Scheduled)" || exit 0
          git push origin update-readme --force